[versions]
foojayVersion = "1.0.0"
graalvmNativeVersion = "0.10.6"
junitVersion = "5.14.3"
licenserVersion = "2.2.2"
micronautApplicationVersion = "4.6.2"
shadowVersion = "9.3.1"

[libraries]
graalvmSvm = { group = "org.graalvm.nativeimage", name = "svm" }
javaxAnnotation = { group = "javax.annotation", name = "javax.annotation-api" }
javaxInject = { group = "javax.inject", name = "javax.inject", version = "1" }
junitBom = { group = "org.junit", name = "junit-bom", version.ref = "junitVersion" }
junitJupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
logbackClassic = { group = "ch.qos.logback", name = "logback-classic" }
micronautGraal = { group = "io.micronaut", name = "micronaut-graal" }
micronautHttpClient = { group = "io.micronaut", name = "micronaut-http-client" }
micronautHttpValidation = { group = "io.micronaut", name = "micronaut-http-validation" }
micronautInjectJava = { group = "io.micronaut", name = "micronaut-inject-java" }
micronautJacksonDatabind = { group = "io.micronaut", name = "micronaut-jackson-databind" }
micronautPicocli = { group = "io.micronaut.picocli", name = "micronaut-picocli" }
micronautRuntime = { group = "io.micronaut", name = "micronaut-runtime" }
micronautRxjava2 = { group = "io.micronaut.rxjava2", name = "micronaut-rxjava2" }
micronautRxjava2HttpClient = { group = "io.micronaut.rxjava2", name = "micronaut-rxjava2-http-client" }
micronautValidation = { group = "io.micronaut.validation", name = "micronaut-validation" }
picocli = { group = "info.picocli", name = "picocli" }
picocliCodegen = { group = "info.picocli", name = "picocli-codegen" }
snakeyaml = { group = "org.yaml", name = "snakeyaml" }

[plugins]
foojay = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "foojayVersion" }
graalvmNative = { id = "org.graalvm.buildtools.native", version.ref = "graalvmNativeVersion" }
licenser = { id = "dev.yumi.gradle.licenser", version.ref = "licenserVersion" }
micronautApplication = { id = "io.micronaut.application", version.ref = "micronautApplicationVersion" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadowVersion" }
